'use strict';

exports.__esModule = true;
var APPLICATION_LOADED = exports.APPLICATION_LOADED = 'APPLICATION_LOADED';
var LOGIN_SUBMITTED = exports.LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';
var LOGIN_SUCCEEDED = exports.LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
var LOGIN_FAILED = exports.LOGIN_FAILED = 'LOGIN_FAILED';
var USER_FETCHED = exports.USER_FETCHED = 'USER_FETCHED';
var USER_FETCH_SUCCEEDED = exports.USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
var USER_FETCH_FAILED = exports.USER_FETCH_FAILED = 'USER_FETCH_FAILED';
var USER_FIRST_FETCH = exports.USER_FIRST_FETCH = 'USER_FIRST_FETCH';
var USER_LOGOUT = exports.USER_LOGOUT = 'USER_LOGOUT';

var TOKEN_DELETED = exports.TOKEN_DELETED = 'TOKEN_DELETED';
var TOKEN_DELETE_SUCCEEDED = exports.TOKEN_DELETE_SUCCEEDED = 'TOKEN_DELETE_SUCCEEDED';
var TOKEN_DELETE_FAILED = exports.TOKEN_DELETE_FAILED = 'TOKEN_DELETE_FAILED';

var WHY = exports.WHY = 'WHY';
var ERROR = exports.ERROR = 'ERROR';
var MESSAGE = exports.MESSAGE = 'MESSAGE';
var FORGET_ERROR = exports.FORGET_ERROR = 'FORGET_ERROR';
var FORGET_MESSAGE = exports.FORGET_MESSAGE = 'FORGET_MESSAGE';
var IS_LOADING = exports.IS_LOADING = 'IS_LOADING';
var DUMP_MESSAGES_FROM_REQUEST = exports.DUMP_MESSAGES_FROM_REQUEST = 'DUMP_MESSAGES_FROM_REQUEST';
var DUMP_ERRORS_FROM_REQUEST = exports.DUMP_ERRORS_FROM_REQUEST = 'DUMP_ERRORS_FROM_REQUEST';