export const APPLICATION_LOADED = 'APPLICATION_LOADED';
export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_FETCHED = 'USER_FETCHED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_FIRST_FETCH = 'USER_FIRST_FETCH';
export const USER_LOGOUT = 'USER_LOGOUT';

export const TOKEN_DELETED = 'TOKEN_DELETED';
export const TOKEN_DELETE_SUCCEEDED = 'TOKEN_DELETE_SUCCEEDED';
export const TOKEN_DELETE_FAILED = 'TOKEN_DELETE_FAILED';

export const WHY = 'WHY';
export const ERROR = 'ERROR';
export const MESSAGE = 'MESSAGE';
export const FORGET_ERROR = 'FORGET_ERROR';
export const FORGET_MESSAGE = 'FORGET_MESSAGE';
export const IS_LOADING = 'IS_LOADING';
export const DUMP_MESSAGES_FROM_REQUEST = 'DUMP_MESSAGES_FROM_REQUEST';
export const DUMP_ERRORS_FROM_REQUEST = 'DUMP_ERRORS_FROM_REQUEST';